src/Entity/Album.php
<?php

namespace App\Entity;

use App\Repository\AlbumRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AlbumRepository::class)]
class Album
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $title = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $release_date = null;

    #[ORM\Column(length: 150)]
    private ?string $artist = null;

    /**
     * @var Collection<int, Song>
     */
    #[ORM\OneToMany(targetEntity: Song::class, mappedBy: 'album')]
    private Collection $songs;

    /**
     * @var Collection<int, Comment>
     */
    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'album')]
    private Collection $comments;

    public function __construct()
    {
        $this->songs = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->release_date;
    }

    public function setReleaseDate(\DateTimeInterface $release_date): static
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getArtist(): ?string
    {
        return $this->artist;
    }

    public function setArtist(string $artist): static
    {
        $this->artist = $artist;

        return $this;
    }

    /**
     * @return Collection<int, Song>
     */
    public function getSongs(): Collection
    {
        return $this->songs;
    }

    public function addSong(Song $song): static
    {
        if (!$this->songs->contains($song)) {
            $this->songs->add($song);
            $song->setAlbum($this);
        }

        return $this;
    }

    public function removeSong(Song $song): static
    {
        if ($this->songs->removeElement($song)) {
            // set the owning side to null (unless already changed)
            if ($song->getAlbum() === $this) {
                $song->setAlbum(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setAlbum($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAlbum() === $this) {
                $comment->setAlbum(null);
            }
        }

        return $this;
    }
}

src/Form/AlbumType.php
<?php

namespace App\Form;

use App\Entity\Album;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AlbumType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('release_date', null, [
                'widget' => 'single_text',
            ])
            ->add('artist')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Album::class,
        ]);
    }
}

src/Controller/AlbumController.php
<?php

namespace App\Controller;

use App\Entity\Album;
use App\Form\AlbumType;
use App\Repository\AlbumRepository;
use App\Repository\CommentRepository;
use App\Repository\SongRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/album')]
class AlbumController extends AbstractController
{
    #[Route('/', name: 'app_album_index', methods: ['GET'])]
    public function index(AlbumRepository $albumRepository): Response
    {
        return $this->render('album/index.html.twig', [
            'albums' => $albumRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_album_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $album = new Album();
        $form = $this->createForm(AlbumType::class, $album);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($album);
            $entityManager->flush();

            return $this->redirectToRoute('app_album_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('album/new.html.twig', [
            'album' => $album,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_album_show', methods: ['GET'])]
    public function show(Album $album, SongRepository  $songRepository, CommentRepository  $commentRepository, Request $request): Response
    {
        $songs = $songRepository->findBy(
            ['album' => $album->getId()],
            ['title'=>'ASC']);
        $comments = $commentRepository->findBy(
            ['album' => $album->getId()],
            ['created_at' => 'DESC'],
        );
        $album_id = $album->getId();
        $id = $request->attributes->get('id');
        // dd($id);
        $user = $this->getUser();
        // dd($user->getUsername(),);
        return $this->render('album/show.html.twig', [
            'album' => $album,
            'songs' => $songs,
            'comments' => $comments,
            // 'user' => $this->getUser()->
        
        ]);
    }

    #[Route('/{id}/edit', name: 'app_album_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Album $album, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AlbumType::class, $album);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_album_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('album/edit.html.twig', [
            'album' => $album,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_album_delete', methods: ['POST'])]
    public function delete(Request $request, Album $album, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$album->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($album);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_album_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/album/_delete_form.html.twig
<form method="post" action="{{ path('app_album_delete', {'id': album.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ album.id) }}">
    <button class="btn">Delete</button>
</form>

templates/album/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/album/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Album{% endblock %}

{% block body %}
    <h1>Edit Album</h1>

    {{ include('album/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_album_index') }}">back to list</a>

    {{ include('album/_delete_form.html.twig') }}
{% endblock %}

templates/album/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Album index{% endblock %}

{% block body %}
{# Afficher les messages flash de succès #}
{% for message in app.flashes('success') %}
    <div class="alert alert-success">
        {{ message }}
    </div>
{% endfor %}

{# Afficher les messages flash d'erreur #}
{% for message in app.flashes('error') %}
    <div class="alert alert-danger">
        {{ message }}
    </div>
{% endfor %}
    <h1>Album index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Release_date</th>
                <th>Artist</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for album in albums %}
            <tr>
                <td>{{ album.id }}</td>
                <td>{{ album.title }}</td>
                <td>{{ album.releaseDate ? album.releaseDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ album.artist }}</td>
                <td>
                    <a href="{{ path('app_album_show', {'id': album.id}) }}">show</a>
                    <a href="{{ path('app_album_edit', {'id': album.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_album_new') }}">Create new</a>
{% endblock %}

templates/album/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Album{% endblock %}

{% block body %}
    <h1>Create new Album</h1>

    {{ include('album/_form.html.twig') }}

    <a href="{{ path('app_album_index') }}">back to list</a>
{% endblock %}

templates/album/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Album{% endblock %}

{% block body %}
    <h1>Album</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ album.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ album.title }}</td>
            </tr>
            <tr>
                <th>Release_date</th>
                <td>{{ album.releaseDate ? album.releaseDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Artist</th>
                <td>{{ album.artist }}</td>
            </tr>
        </tbody>
    </table>

    <div class="album_song container">
            <h5 class="text-center">Les sons de l'album </h5>
            <div class="row my-4"  id='songList'>
                {% for song in songs %}
                    <div class="col-3 mx-2 my-4 text-center">
                        <div class="card">
                            <h6 class="card-title">
                               Titre : {{ song.title }}
                            </h6>
                            <p class="card-text">
                            Durée : {{ song.duration }}s

                            </p>
                        </div>
                    </div>
                    
                {% endfor %}
            
            </div>
             <div class="row my-4"  id='songList'>
                    <h5 class="text-center">Les commentaires de cet album </h5>
                {% for comment in comments %}
                    <div class="col-3 mx-2 my-4 text-center">
                        <div class="card">
                            <h6 class="card-title">
                               Titre : 
                               {{ comment.content }}
                            </h6>
                            <p class="card-text">
                           {# Durée : {{ comment.Created_at|date('d/m/Y à H:i') }} #}
                           Durée : {{ comment.CreatedAt|date('d/m/Y à H:i') }}
                            </p>
                            <p>
                            {{ include('./comment/_delete_form.html.twig') }}                            
                            </p>
                        </div>
                    </div>
                {% else %}
                <p> Aucun commentaire pour cet album </p>
                    
                {% endfor %}
                    
            
            </div>
                    <a href="{{path('app_add_comment', {'album_id': album.id})}}" class="btn btn-primary" > Ajouter un commentaire</a>
    </div>

    <a href="{{ path('app_album_index') }}">back to list</a>

    <a href="{{ path('app_album_edit', {'id': album.id}) }}">edit</a>

    {{ include('album/_delete_form.html.twig') }}
{% endblock %}